server:
  port: 8040
spring:
  application:
    name: gateway-zuul
zuul:
  routes:
    user-route:
      url: http://localhost:8080/user
      path: /user/**
  ratelimit:
    enabled: true
    default-policy:
      limit: 2
      quota: 2
      refresh-interval: 3
      type: origin